### ISSUE TITLE
my nsis function symbol list script...ugly code, while worked!

### ISSUE THREAD

**Issue by saleo** [NSIS-Dev/sublime-nsis-ide#3]
![image](https://user-images.githubusercontent.com/2926834/40618778-29b0ea38-62c5-11e8-8c8c-dbde68035508.png)

1. add below code before any exising rows containing "Function"  in file "NSIS.sublime-syntax"
```
    - match: ^\s*(?i)(Function|Section)\b
      scope: name.function.nsis
      push:
        - meta_scope: entity.name.function.nsis
        - match: '\s?((un\.)?){{identifier}}'
          scope: e1.entity.name.function.nsis
          pop: true
```

2. save below code as filename "symbol list pragma.tmPreferences" under NSIS-ide package,mine is "D:\portableApps\sublimeText3\Data\Packages\NSIS Developer\Symbol List Pragma.tmPreferences"

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Symbol List</string>
    <key>scope</key>
    <string>entity.name.function.nsis</string>
    <key>settings</key>
    <dict>
        <key>showInSymbolList</key>
        <integer>1</integer>
        <key>showInIndexedSymbolList</key>
        <integer>0</integer>
    </dict>
</dict>
</plist>
```
